name: Manage Issues for Try and Solve Commits

on:
  push:
    branches:
      - main # Adjust this to your default branch if needed

permissions:
  issues: write # Required for creating and closing issues
  contents: read # Required for actions/checkout

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the last two commits to get the latest commit message

      - name: Check commit message for 'try' or 'solve' and extract URL
        id: check_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          URL=$(echo "$COMMIT_MESSAGE" | grep -oE 'https?://[^ ]+' | head -n 1)
          if [ -n "$URL" ]; then
            ENCODED_URL=$(echo "$URL" | base64 -w 0)
            echo "problem_url=$ENCODED_URL" >> $GITHUB_OUTPUT
          else
            echo "problem_url=none" >> $GITHUB_OUTPUT
          fi
          if [[ "$COMMIT_MESSAGE" =~ [Tt][Rr][Yy] ]]; then
            echo "action=try" >> $GITHUB_OUTPUT
            echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
            echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          elif [[ "$COMMIT_MESSAGE" =~ [Ss][Oo][Ll][Vv][Ee] ]]; then
            echo "action=solve" >> $GITHUB_OUTPUT
          else
            echo "action=none" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Issue for 'try'
        if: steps.check_commit.outputs.action == 'try' && steps.check_commit.outputs.problem_url != 'none'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitMessage = '${{ steps.check_commit.outputs.commit_message }}';
            const commitSha = '${{ steps.check_commit.outputs.commit_sha }}';
            const encodedUrl = '${{ steps.check_commit.outputs.problem_url }}';
            const problemUrl = Buffer.from(encodedUrl, 'base64').toString('utf-8');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Link to Problem: Commit ${commitSha推理
